"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import type { CatalogItem } from "@/features/catalog/domain/catalog-item";
import { formatMxn } from "@/features/pricing/domain/price-calculator";
import { readCart, resolveCartItem, writeCart, type CartEntry } from "../application/cart-storage";

type Platform = "epic" | "xbox" | "playstation" | "nintendo";

export function CartCheckoutForm({ items }: { items: readonly CatalogItem[] }) {
  const router = useRouter(); const [cart, setCart] = useState<CartEntry[]>([]); const [email, setEmail] = useState(""); const [receiverId, setReceiverId] = useState(""); const [platform, setPlatform] = useState<Platform>("epic"); const [whatsapp, setWhatsapp] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const frame = window.requestAnimationFrame(() => setCart(readCart())); return () => window.cancelAnimationFrame(frame); }, []);
  const lines = useMemo(() => cart.flatMap((entry) => { const item = resolveCartItem(entry, items); return item ? [{ item }] : []; }), [cart, items]);
  const total = lines.reduce((sum, line) => sum + (line.item.priceMxn ?? 0), 0);
  const hasPendingPrice = lines.some((line) => line.item.priceMxn === null);
  async function submit(event: FormEvent) { event.preventDefault(); if (!lines.length || hasPendingPrice) return; setLoading(true); setError(null); const response = await fetch("/api/cart-orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customerEmail: email, receiverId, platform, whatsapp, items: lines.map((line) => ({ itemMainId: line.item.mainId, quantity: 1 })) }) }); const body = await response.json(); setLoading(false); if (!response.ok) { setError(body.error ?? "No fue posible crear tu solicitud."); return; } writeCart([]); router.push(`/pedidos/${body.order.id}?access=${body.order.publicToken}`); }
  if (!lines.length) return <section className="flow-shell"><div className="flow-heading"><p className="eyebrow">SOLICITUD</p><h1>Tu carrito está vacío.</h1><Link className="primary-button" href="/#catalogo">Explorar tienda</Link></div></section>;
  return <section className="flow-shell"><div className="flow-heading"><p className="eyebrow">PASO FINAL</p><h1>Confirma tu solicitud.</h1><p>Un supervisor revisará tu pedido y podrá contactarte al número proporcionado.</p></div><form className="checkout-card" onSubmit={submit}><div className="order-summary"><div><p className="eyebrow">TU PEDIDO</p><h2>{lines.length} {lines.length === 1 ? "objeto" : "objetos"}</h2><span>Una unidad de cada objeto</span></div><strong>{formatMxn(total)}</strong></div><div className="checkout-items">{lines.map(({ item }) => <p key={item.mainId}><span>{item.name}</span><strong>{item.priceMxn === null ? "Consultar" : formatMxn(item.priceMxn)}</strong></p>)}</div><label>Correo electrónico<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="tu@correo.com" /></label><div className="account-fields"><label>ID que recibirá los objetos<input required minLength={3} maxLength={128} value={receiverId} onChange={(event) => setReceiverId(event.target.value)} placeholder="Tu ID de juego" /></label><label>Plataforma<select value={platform} onChange={(event) => setPlatform(event.target.value as Platform)}><option value="epic">Epic Games</option><option value="xbox">Xbox</option><option value="playstation">PlayStation</option><option value="nintendo">Nintendo Switch</option></select></label></div><label>WhatsApp de contacto<input required inputMode="tel" pattern="[0-9+ ()-]{8,24}" value={whatsapp} onChange={(event) => setWhatsapp(event.target.value)} placeholder="55 5555 5555" /></label>{hasPendingPrice && <p className="notice error">Uno o más objetos están pendientes de precio; puedes conservarlos en el carrito, pero aún no es posible confirmarlos.</p>}<p className="notice">Al confirmar, un supervisor recibirá tu solicitud dentro de la plataforma. Podrás consultar el avance desde Mis compras.</p>{error && <p className="notice error">{error}</p>}<button className="primary-button" disabled={loading || hasPendingPrice}>{loading ? "Creando solicitud…" : "Confirmar pedido"}</button><Link className="cart-secondary" href="/carrito">Volver al carrito</Link></form></section>;
}
